### ISSUE TITLE
do you have 3.5seb

### ISSUE THREAD

**Issue by 2801980142** [SUPE4COOKIE/SEB-vm-escape#1]
dll cannot be used with new version 3.5

**Comment by SUPE4COOKIE** [comment]
updated it, and added functionality to (kinda) open apps on guest machine
i haven't tested this version a lot please report any issue that you have

**Comment by 2801980142** [comment]
hi，I used the new dll, but after about 25-30 minutes, seb locked my computer and prompted me to use an unofficial program
